config/routes.rb
Uniphobia::Application.routes.draw do

  get "comments/create"

  get "comments/destroy"

  resources :posts do
    resources :comments
  end

resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions,          only: [:new, :create, :destroy]
  resources :microposts,        only: [:create, :destroy]
  resources :relationships,      only: [:create, :destroy]

  match '/signup',              to: 'users#new'
  match '/signup_vorlesung',    to: 'users#new_vorlesung' 
  match '/signup_semester',     to: 'users#new_semester' 
  match '/signup_uni',          to: 'users#new_uni' 
  match '/signin',              to: 'sessions#new'
  match '/signinerror',         to: 'sessions#newerror'
  match '/signout',             to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/mitmachen',   to: 'static_pages#mitmachen'
  match '/help',        to: 'static_pages#help'
  match '/about',       to: 'static_pages#about'
  match '/contact',     to: 'static_pages#contact'
  match '/codebase',    to: 'static_pages#codebase'
  match '/datenschutz', to: 'static_pages#datenschutz'
  match '/cookies',     to: 'static_pages#cookies'
  match '/impressum',   to: 'static_pages#impressum'
  match '/uni',         to: 'users#uni'

end

app/views/layouts/_carousel.html.erb
<header class="jumbotron_masthead">
	<div class="container center">
	  <h1 class="h1_main">UN!PHOBIA</h1>
	  <h2 class="h2_main">
	    Wer will schon zur Vorlesung gehen!?
	  </h2>
	  <%= link_to "Registrierung!", signup_path, class: "btn btn-large btn-inverse buttonmargin" %>
	</div>
</header>
<div class="container">
	<div class="row">
		<div class="span10 offset1">
			<div class="marketing center">
				<div id="myCarousel" class="carousel slide">
				  <!-- Carousel items -->
				  <div class="carousel-inner">
				    <div class="active item"><%= image_tag("carousel_001.png", alt: "screenshot1") %></div>
				    <div class="item"><%= image_tag("carousel_002.png", alt: "screenshot2") %></div>
				    <div class="item"><%= image_tag("carousel_003.png", alt: "screenshot3") %></div>
				    <div class="item"><%= image_tag("carousel_004.png", alt: "screenshot4") %></div>
				    <div class="item"><%= image_tag("carousel_005.png", alt: "screenshot5") %></div>
				  </div>
				  <!-- Carousel nav -->
				  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
				  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      <a href="http://seliegdesign.herokuapp.com/"></a>
      copyright UN!PHOBIA 2012
    </small>
    <nav>
      <ul class="footer-rechts">
        <li><%= link_to "Über uns |",   about_path %></li>
        <li><%= link_to "Kontakt |", contact_path %></li>
        <li><%= link_to "Datenschutz |", datenschutz_path %></li>
        <li><%= link_to "Cookies |", cookies_path %></li>
        <li><%= link_to "Impressum/Nutzungsbedingungen", impressum_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "UN!PHOBIA", root_path, id: "logo" %>
        <nav class="nav- pull-right">
          <ul class="nav">
            <li><%= link_to "HOME", root_path %></li>
            <li><%= link_to "MITMACHEN", mitmachen_path %></li>            
      <% if signed_in? %>
            <li><a href="/uni"><i class="icon-search icon-white"></i> UNIS</a></li>
            <li><a href="/users"><i class="icon-search icon-white"></i> USERS</a></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">ACCOUNT <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profil", current_user %></li>
                <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Abmelden", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% if user_be_admin? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-star icon-white"></i> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Vorlesung erstellen",  signup_vorlesung_path %></li>
                <li><%= link_to "Semester erstellen",   signup_semester_path %></li>
                <li><%= link_to "Uni erstellen",        signup_uni_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Codebase", codebase_path %></li>
                <li><%= link_to "Le Basecamp", posts_path %></li>
                <li><%= link_to "Abmelden", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% end %>   
      <% else %>
            <form class="form-inline" accept-charset="UTF-8" action="/sessions" method="post"> 
              <input id="session_email" name="session[email]" type="text" class="input-small" placeholder="Email">
              <input id="session_password" name="session[password]" type="password" class="input-small" placeholder="Password">
              <input class="btn btn-large btn-warning login" name="commit" type="submit" value="Sign in">
            </form>  
      <% end %>     
          </ul>
        </nav>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  
  <body>
    <%= render 'layouts/navbar' %>
      <%= yield %>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
    <script>
      $('.carousel').carousel({
        interval: 5000
        })
    </script>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>